// <auto-generated />
using System;
using GamingTurnir.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingTurnir.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GamingTurnir.Models.ClanTima", b =>
                {
                    b.Property<int>("ClanTimaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClanTimaId"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("TimId")
                        .HasColumnType("int");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ClanTimaId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("TimId");

                    b.ToTable("ClanoviTima");
                });

            modelBuilder.Entity("GamingTurnir.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<DateTime>("DatumRegisdtracije")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rola")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KorisnikId");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("GamingTurnir.Models.Mec", b =>
                {
                    b.Property<int>("MecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MecId"));

                    b.Property<DateTime>("DatumMeca")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RezultatTim1")
                        .HasColumnType("int");

                    b.Property<int?>("RezultatTim2")
                        .HasColumnType("int");

                    b.Property<int>("Tim1Id")
                        .HasColumnType("int");

                    b.Property<int>("Tim2Id")
                        .HasColumnType("int");

                    b.Property<int>("TurnirId")
                        .HasColumnType("int");

                    b.HasKey("MecId");

                    b.HasIndex("Tim1Id");

                    b.HasIndex("Tim2Id");

                    b.HasIndex("TurnirId");

                    b.ToTable("Mecevi");
                });

            modelBuilder.Entity("GamingTurnir.Models.Tim", b =>
                {
                    b.Property<int>("TimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TimId"));

                    b.Property<DateTime>("DatumOsnivanja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TimId");

                    b.ToTable("Timovi");
                });

            modelBuilder.Entity("GamingTurnir.Models.Turnir", b =>
                {
                    b.Property<int>("TurnirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TurnirId"));

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Igrica")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TurnirId");

                    b.ToTable("Turniri");
                });

            modelBuilder.Entity("GamingTurnir.Models.ClanTima", b =>
                {
                    b.HasOne("GamingTurnir.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingTurnir.Models.Tim", "Tim")
                        .WithMany("Clanovi")
                        .HasForeignKey("TimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Tim");
                });

            modelBuilder.Entity("GamingTurnir.Models.Mec", b =>
                {
                    b.HasOne("GamingTurnir.Models.Tim", "Tim1")
                        .WithMany("MeceviKaoTim1")
                        .HasForeignKey("Tim1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamingTurnir.Models.Tim", "Tim2")
                        .WithMany("MeceviKaoTim2")
                        .HasForeignKey("Tim2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamingTurnir.Models.Turnir", "Turnir")
                        .WithMany("Mecevi")
                        .HasForeignKey("TurnirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tim1");

                    b.Navigation("Tim2");

                    b.Navigation("Turnir");
                });

            modelBuilder.Entity("GamingTurnir.Models.Tim", b =>
                {
                    b.Navigation("Clanovi");

                    b.Navigation("MeceviKaoTim1");

                    b.Navigation("MeceviKaoTim2");
                });

            modelBuilder.Entity("GamingTurnir.Models.Turnir", b =>
                {
                    b.Navigation("Mecevi");
                });
#pragma warning restore 612, 618
        }
    }
}
